//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTU.EFDB.FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCompany
    {
        public int ID { get; set; }
        public Nullable<int> SystemUserID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string TelephoneNumberI { get; set; }
        public string TelephoneNumberII { get; set; }
        public string TelephoneNumberIII { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public override string ToString()
        {
            return $"{Title}";
        }
    }
}
