//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTU.EFDB.FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YTUProjectEntities : DbContext
    {
        public YTUProjectEntities()
            : base("name=YTUProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
          
        }
    
        public virtual DbSet<CustomerCompany> CustomerCompanies { get; set; }
        public virtual DbSet<systemUser> systemUsers { get; set; }
    }
}
