//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTU.EFDB.FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerHistory
    {
        public int ID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> stateCode { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
