//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTU.EFDB.FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProductList
    {
        public int ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
