//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTU.EFDB.FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string ProductNumber { get; set; }
        public string Color { get; set; }
        public Nullable<int> SafetyStockLevel { get; set; }
        public Nullable<decimal> StandartCost { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public string Size { get; set; }
    }
}
